### ISSUE TITLE
home button not quite right

### ISSUE THREAD

**Issue by danmermel** [glynnbird/rss#24]
if you hit Home from the newsfeed page you get
http://d7rndzct013phmlp2vqq.s3-website-eu-west-1.amazonaws.com/newsfeed/newsfeed

if you hit home from the add feed page you get http://d7rndzct013phmlp2vqq.s3-website-eu-west-1.amazonaws.com/addfeed/newsfeed

So basically we are not constructing that url correctly... I suspect there is a slash missing somewhere.

**Comment by danmermel** [comment]
actually, it works fine on localhost but not on the deployed site.... so something to do with how the routes are interpreted?

**Comment by glynnbird** [comment]
Could be because we're using relative URLs sometimes: like here https://github.com/glynnbird/rss/blob/8bbd2a0aa850e42bf0640083be24ee8f33330fe3/frontend/pages/index.vue#L29

should have a forward slash in front?
